### ISSUE TITLE
Get neighbors even if empty

### ISSUE THREAD

**Issue by Ziboo** [AurelWu/HexMapLibrary#1]
Hi,

First of all, awesome library, thank you very much for sharing that.
I have a small issue and I wanted your though about it.
I need to check neighbors of a tile to find the Cover I would have (like XCom).
Right now with the library if you ask the neighbors , you automatically remove orphans.
I need to have all tiles in the right order (clockwise)

So I did that:

`var edges = BoardManager.Instance.HexMap.GetEdgePositions.OfTile(this.currentTile.Position);

            for (var i = 0; i < edges.Count; i++)
            {
                var edge = edges[i];
                var tiles = BoardManager.Instance.HexMap.GetTiles.AdjacentToEdge(edge);
                var ortherTile = tiles.FirstOrDefault(x => x != this.currentTile);
                if (ortherTile != null)
                {
                    //Tile exists and is in a clockwise order
                }
            }`
I wanted to know if there was a better way ?

Thanks !

**Comment by AurelWu** [comment]
Hi, what do you mean by orphans? It just "removes" tiles which are out of the bounds of the map.
If you really want to get those tiles which are outside of your map bounds you can use the static HexGrid class instead of HexMap.
If I misunderstood you, can you please try to explain it a bit more in depth (maybe with a simple annotated drawing?)

**Comment by Ziboo** [comment]
Yes I meant having tiles outside the map too. A function that will always return 6 tiles, in the same order, all the time. I'll try the static method then when I'm back from holidays. Thank you

**Comment by AurelWu** [comment]
Did you manage to do what you wanted to do without resorting to any too round-about solution?

**Comment by Ziboo** [comment]
Hello AurelWu,

So came back to the project and yes, the static function HexGrid works exactly like I needed !
Thanks !
