### ISSUE TITLE
Missing documentation on how to import library

### ISSUE THREAD

**Issue by david-pfx** [AurelWu/HexMapLibrary#5]
The README needs a brief comment on how to import the library into a project.

The first tutorial says "we first need to import our library into unity: [TODO IMAGE]" but does not explain how to do that (other than downloading the completed set of examples).

**Comment by AurelWu** [comment]
updated the ReadMe; also added a sentence to first tutorial explaining step by step how to import a unitypackage. Image seemed overkill for what can be described in a few words)

**Comment by david-pfx** [comment]
Agreed. But you might want to take a look at the spelling.

**Comment by AurelWu** [comment]
Holy... I have no idea how that happened... thanks, fixed.
